### ISSUE TITLE
Add optional parameters

### ISSUE THREAD

**Issue by nlubisch** [shopwareLabs/psh#75]
If you add a placeholder in your script and omit the option on the CLI a RuntimeException is thrown.
```
PHP Fatal error:  Uncaught RuntimeException: Missing required value for "PROVISION" in phar:///.../src/ScriptRuntime/TemplateEngine.php:55
Stack trace:
#0 phar:///.../src/ScriptRuntime/TemplateEngine.php(26): Shopware\Psh\ScriptRuntime\TemplateEngine->getValue('__PROVISION__', Array)
#1 phar:///.../src/ScriptRuntime/ProcessExecutor.php(117): Shopware\Psh\ScriptRuntime\TemplateEngine->render('echo "__PROVISI...', Array)
#2 phar:///.../src/ScriptRuntime/ProcessExecutor.php(66): Shopware\Psh\ScriptRuntime\ProcessExecutor->getParsedShellCommand(Object(Shopware\Psh\ScriptRuntime\ProcessCommand))
#3 phar:///.../src/Application/Application.php(170): Shopware\Psh\ScriptRuntime\ProcessExecutor->execute(Object(Shopware\Psh\Listing\Script), Array)
#4 phar:///.../p in phar:///.../src/ScriptRuntime/TemplateEngine.php on line 55
```

Instead of throwing the Exception i would expect a default value if the option is not passed, so that i can handle whether the option is passed or not.

**Comment by teiling88** [comment]
It is already possible - define your default value in you .psh.yaml file :-)

**Comment by nlubisch** [comment]
Thanks, thats it!
